<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ ucfirst($reportType) }} Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Arial', sans-serif;
            font-size: 11px;
            line-height: 1.5;
            color: #333;
            padding: 20px;
        }

        .header {
            text-align: center;
            border-bottom: 3px solid #000;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }

        .header h1 {
            font-size: 20px;
            font-weight: bold;
            text-transform: uppercase;
            margin-bottom: 5px;
        }

        .header .subtitle {
            font-size: 14px;
            color: #666;
        }

        .report-info {
            margin-bottom: 25px;
            padding: 10px;
            background-color: #f5f5f5;
            border-left: 4px solid #333;
        }

        .section {
            margin-bottom: 25px;
        }

        .section-title {
            font-size: 14px;
            font-weight: bold;
            text-transform: uppercase;
            background: #333;
            color: #fff;
            padding: 8px 12px;
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }

        th {
            background-color: #f0f0f0;
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }

        td {
            border: 1px solid #ddd;
            padding: 6px 8px;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .summary-box {
            display: inline-block;
            width: 30%;
            margin-right: 3%;
            padding: 10px;
            border: 2px solid #333;
            text-align: center;
            margin-bottom: 10px;
        }

        .summary-label {
            font-size: 10px;
            color: #666;
            text-transform: uppercase;
        }

        .summary-value {
            font-size: 18px;
            font-weight: bold;
            margin-top: 5px;
        }

        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 2px solid #000;
            text-align: center;
            font-size: 9px;
            color: #666;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ setting('general.site_name', 'Dr. V Aesthetic Clinic') }}</h1>
        <div class="subtitle">{{ ucfirst($reportType) }} REPORT</div>
    </div>

    <div class="report-info">
        <strong>Report Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('F d, Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('F d, Y') }}<br>
        <strong>Generated:</strong> {{ now()->format('F d, Y g:i A') }}<br>
        <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}
    </div>

    @if($reportType === 'financial')
        @include('reports.pdf.financial')
    @elseif($reportType === 'appointments')
        @include('reports.pdf.appointments')
    @elseif($reportType === 'services')
        @include('reports.pdf.services')
    @elseif($reportType === 'clients')
        @include('reports.pdf.clients')
    @elseif($reportType === 'staff')
        @include('reports.pdf.staff')
    @endif

    <div class="footer">
        <p><strong>{{ setting('general.site_name', 'Dr. V Aesthetic Clinic') }}</strong></p>
        <p>Confidential Report - For Internal Use Only</p>
        <p>Generated: {{ now()->format('F d, Y \a\t g:i A') }}</p>
    </div>
</body>
</html>

